# This is a basic workflow to help you get started with Actions

name: Main Workflow

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Build
        uses: actions/checkout@v4
      - run: ci/build-app.sh
      - name: test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true
   
