# This is a basic workflow to help you get started with Actions

name: Main Workflow

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Build and Test
        uses: actions/checkout@v4
      - run: ci/build-app.sh
